### Login to the database
POST  http://localhost:3000/auth/login
Content-Type: application/json

{
    "email":"njohn.doe@example.com",
    "password": "$2a$12$rwQtaoimRlcBMJu1OFYJV.C7wHDnKRJwZvOGRngJ5I1w7AEiYqZd."
}

### Get User
GET http://localhost:3000/auth/user/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJuam9obi5kb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3MzY0MTQwNjEsImV4cCI6MTczNjQxNzY2MX0.OvT-mODYhjJxmhUF_m0qwDkHtJzfU1XRO2KQ0pyNo9k

### Get all organisation
GET http://localhost:3000/api/organisations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJuam9obi5kb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3MzY0MTQwNjEsImV4cCI6MTczNjQxNzY2MX0.OvT-mODYhjJxmhUF_m0qwDkHtJzfU1XRO2KQ0pyNo9k

### Create Organisation
POST http://localhost:3000/api/organisations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJqb2huLmRvZUBleGFtcGxlLmNvbSIsImlhdCI6MTczNjM3ODQ2NCwiZXhwIjoxNzM2NTA4MDY0fQ.83mMO74QIidSdjq8UWS5VeEJ2lkp5f2UWPNn_ES3Qfg

{
    "name":"My Organisation",
    "description":"This is my new organisation"
}

### Add user to organisation
POST http://localhost:3000/api/organisations/3/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJzYW0uYWRhbXNAZXhhbXBsZS5jb20iLCJpYXQiOjE3MzYzNzE5NDQsImV4cCI6MTczNjUwMTU0NH0.CZdeIHxhqAcwUVAbY2Hldi521XcPJEzpDupeEaYe0Bo

{
    "userId": "3"
}

### Get Single Organisation
GET http://localhost:3000/api/organisations/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJuam9obi5kb2VAZXhhbXBsZS5jb20iLCJpYXQiOjE3MzY0MTQwNjEsImV4cCI6MTczNjQxNzY2MX0.OvT-mODYhjJxmhUF_m0qwDkHtJzfU1XRO2KQ0pyNo9k


### Register into the database
POST  http://localhost:3000/auth/register
Content-Type: application/json

# {
#     "firstName" : "nJohn",
#     "lastName" : "nDoe",
#     "email" : "njohn.doe@example.com",
#     "password" : "NSecurePassword123",
#     "phone" : "21234567890"
# }

# {
#     "firstName" : "Jane",
#     "lastName" : "Smith",
#     "email" : "jane.smith@example.com",
#     "password" : "password@456",
#     "phone" : "9876543210"
# }

# {
#     "firstName" : "Samuel",
#     "lastName" : "Adams",
#     "email" : "sam.adams@example.com",
#     "password" : "SamStrog789",
#     "phone" : "5647382910"
# }